language: java
jdk:
- oraclejdk8
script:
- gradle
before_script:
- psql -c 'create database itevent_test_db;' -U postgres
- psql -c 'create database itevent_db;' -U postgres
addons:
  postgresql: '9.3'
services:
- postgresql
deploy:
  provider: openshift
  user: anttoshka@gmail.com
  password:
      secure: "lfNt1DpzneBscCbRmnP1+yZWRphBWA+uZl5z+D+LU5bjqNs08ie3CNRGeJovlBuOUE4E5A9y2PTr+3o1GDqOICpBt/O5/GgwDd7kN0O+365M1Thjylj75jMqvIEzdxv/zyc8nb
    YUcL8sTnvuhmYKtincNHfM5yjPOkjFH8GujwSNzspsdgBYZu/yOYlA9C47zC7i5dgxEZ6tk2k0+I8Vl8uwkvy8/+SZ5eICD9sp5biOKCJYrT91fX/3Dm8sHQV2Mr9gW/OOUQODPHW8uQN0Z6q
    cMb44xag541jmoRxFGb9eSZqTtqrSFeOFd7XDJhc8S4VMOhr3oHDEJ8nufdAfXaJkEeDLRjsyqTNRmuARo6kJ/abTukMm0LTY4HsRHpKCst5hBV9KZwH+Kzp1tiZ5BJB2Vb/xrZjBK1svRocb
    BvmeZDUGGbkzBrmfuViKL/D3Tyh4a6kt2EfBlSTECjvoDv2pspDXbuKLeFQwOi/sUumQbTn+rQ1/gOG6cyKS0/TX+1w4OLbfSKFOh+/89kVxttnrxgnkf7smKwP+knsVgq6LkoJqJ9S4Km7u1
    rqqg7LHW/hLL29E93noINRE+Qn0Jy66npGq2O/B/68HLewCtT1TBBCS0C+ZgpcHgIO3vsx+9TC0ZJLdchfDL1guYWhhuttvGaBcinSgFWwxfs6cjX8="
  app: test
  domain: iteventstest
  on:
    repo: Antonerof/tomcat
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -m "Travis change"
